server:
  port: 
spring:
  datasource:
    url: 
    username: 
    password: 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
  mail:
    host: smtp.huawei.com
    username: 
    password: 
    port: 25
    protocol: smtp
mail:
  fromMail:
    addr: 
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
espace:
  send-url: 
